### ISSUE TITLE
Differences between word2index & index2word in Voc

### ISSUE THREAD

**Issue by Dr-Corgi** [ywk991112/pytorch-chatbot#13]
Hi @ywk991112 ,
I read the code in **load.py**, 
it seems that the **_word2index_** and **_index2word_** are not consistent.  
  
I add these code in the **load.py** to test Voc:

    if __name__ == "__main__":
        voc, pairs = loadPrepareData("./data/movie_subtitles.txt")
        print(voc.word2index['SOS'])                    # 20565
        print(voc.word2index['EOS'])                    # KeyError
        print(voc.word2index['PAD'])                    # KeyError
        print(voc.index2word[0])                          # 'SOS'
        print(voc.index2word[1])                          # 'EOS' 
        print(voc.index2word[2])                          # 'PAD'

It seems that we should initialize the self.word2index in the function __init__(), isn't it?

Even though, I did not read through the entire project yet, so I am not sure whether this inconsistence will influence the performance of the model...

**Comment by ywk991112** [comment]
SOS_token is used as the first input in decoding step, it won't appear in decoding output.
So 'SOS' won't mess up with 'SOS_token'.
