### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by qtli** [ywk991112/pytorch-chatbot#2]
MacBook-Pro:pytorch-chatbot-master mac$ python main.py -tr <data/corpus.txt> -la 1 -hi 512 -lr 0.0001 -it 50000 -b 64 -p 500 -s 1000
  File "main.py", line 40
    args.reverse, args.filter, args.iteration, args.print, args.save, args.learning_rate, \
                                                        ^
SyntaxError: invalid syntax

I was confused by this issue for a long time, I really want to know if there was error in my command??  thank you very much.

**Comment by ywk991112** [comment]
Maybe you should run the code in python3 instead of python2.
