### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by kuwo88** [ywk991112/pytorch-chatbot#4]
File "main.py", line 40
    args.reverse, args.filter, args.iteration, args.print, args.save, args.learning_rate, \
                                                        ^
SyntaxError: invalid syntax

How should I solve it

**Comment by kuwo88** [comment]
I have encountered some problems and methods to solve compatibility problems. [Pytorch seq2seq聊天机器人(pytorch-chatbot)](https://ptorch.com/news/137.html)

**Comment by ywk991112** [comment]
You have the same issue as #2 . Run the code with python3 instead of python2 may help.
