### ISSUE TITLE
training speed is slow

### ISSUE THREAD

**Issue by Tangzy7** [ywk991112/pytorch-chatbot#6]
Using gpu, the training speed is 4s/iteration when the batch size is 64. It is quite of slow. 
I want to know your training speed.

**Comment by ywk991112** [comment]
The training speed is 2.x sec/iter while using GTX 1080.
Any way to speed up the training is welcome to comment below.

**Comment by Tangzy7** [comment]
@ywk991112 Hi, I want to know what paramter you used to get 2.x sec/iter. I used the default setting -la 1 -hi 512 -lr 0.0001 -it 50000 -b 64 -p 500 -s 1000 with MAX_LENGTH=15 on nvidia P100.

**Comment by Tangzy7** [comment]
@ywk991112 Hi, I want to know what paramter you used to get 2.x sec/iter. I got 4.x sec/iter when using the default setting -la 1 -hi 512 -lr 0.0001 -it 50000 -b 64 -p 500 -s 1000 with MAX_LENGTH=15 on nvidia P100.

**Comment by ywk991112** [comment]
I use the default setting and got 2.68s/it on GTX 1080 Ti.
![screenshot from 2018-04-10 10-34-20](https://user-images.githubusercontent.com/8744148/38533233-e3c41efe-3caa-11e8-8a4a-54669e2d3b5d.png)

**Comment by Tangzy7** [comment]
I just found that for-loop in pytorch will decrease the speed of both forward and backward, just like the for-loop here.

`        for t in range(max_target_len):
            decoder_output, decoder_hidden, decoder_attn = decoder(
                decoder_input, decoder_hidden, encoder_outputs
            )`

I just vectorized the input of decoder and only used teacher-forcing, and got a speed of 21 it/s with 256 batch size. Previewly ,it's 16 s/it

**Comment by Crescentz** [comment]
why your attn:
![rgu4 fge4 6tn 7si2 _dt](https://user-images.githubusercontent.com/35165563/50401359-e480a300-07c8-11e9-937f-29fe5bf2cb18.png)
pytroch:
![image](https://user-images.githubusercontent.com/35165563/50401374-ff531780-07c8-11e9-9b0f-7727dcdec287.png)

After modification to the PYTORCH document:
speed up~~~~~~~~~~~~~~

Can you explain that?
