### ISSUE TITLE
A bug in beam decode

### ISSUE THREAD

**Issue by Tangzy7** [ywk991112/pytorch-chatbot#8]
https://github.com/ywk991112/pytorch-chatbot/blob/master/evaluate.py#L59

Do you need to add the following line [here](https://github.com/ywk991112/pytorch-chatbot/blob/master/evaluate.py#L59):
decoder_hidden = sentence.decoder_hidden

The current beam_decode used  previous sentence's decoder_hidden but not its own decoder_hidden

**Comment by ywk991112** [comment]
Yes! Thanks for the correction.
